<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSPxfnxp\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSPxfnxp/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerSPxfnxp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerSPxfnxp\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerSPxfnxp\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'SPxfnxp',
    'container.build_id' => '7d2d4f75',
    'container.build_time' => 1623742447,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSPxfnxp');
